### ISSUE TITLE
Problems with uefi

### ISSUE THREAD

**Issue by Dinico414** [WOA-Project/SurfaceDuo-Guides#14]
when i want to boot to windows the comand
`fastboot boot surfaceduo1-uefi.img`
is not working!

i need to put the _uefi.img_ file in the adb direcory AND change the code to
`fastboot boot uefi.img`
then it worked

would be great if this would stand in the skript as well

**Comment by gus33000** [comment]
Hello! Thanks for bringing this to our attention! The guide does still need a bit of clarifications in general.

Just as a note: you can name the file anything you want really. You can even specify a full path to the file if you would like to, there's plenty of possibilities. We can clarify this further, but we feel like it's a basic command line step in that regard anyone may be able to adapt on their own.
