### ISSUE TITLE
After modify power plan to never sleep, win11 would not to boot

### ISSUE THREAD

**Issue by NoviaDroid** [WOA-Project/SurfaceDuo-Guides#17]
after enter "fastboot boot surfaceduo1-uefi.img" , can see windows boot menu,

but after choose win11 to boot, surface duo auto power off after a while and failed to boot into win11.

It is a fresh new install of win11 with no change to other settings other then power plan and text scale settings

**Comment by gus33000** [comment]
is this still happening? are you able to provide more context as to what you changed/did to the power plan?

**Comment by NoviaDroid** [comment]
after update to the latest driver, not happened so far
