### ISSUE TITLE
Charging functionality is not yet available under Windows

### ISSUE THREAD

**Issue by TechXPlays** [WOA-Project/SurfaceDuo-Guides#28]
figured I'd just edit this instead of creating something else. Is there a fix for this or is it a bug?

**Comment by gus33000** [comment]
Charging is not currently available (See status page). It may be available soon or in a while. You can charge in android for now.

**Comment by daanta-real** [comment]
https://github.com/WOA-Project/SurfaceDuo-Guides/blob/main/Status.md look at the "Global progress" table in the middle of the page. It says the Charger feature is being incubated.

**Comment by gus33000** [comment]
Yes, incubating means we're working on it and testing it, doesn't mean it's available
