### ISSUE TITLE
[256GB Device] UEFI Shell loads, not Development Menu

### ISSUE THREAD

**Issue by JengaMasterG** [WOA-Project/SurfaceDuo-Guides#3]
I am testing with a 256GB device, and I noticed a few things:

1. I get a tar chown 1000:1000 Operation not permitted warning with several files when I untar the DuoBoot tar file.
2. If I continue with the guide, the UEFI Shell boots up no problem. The **left** screen displays the information and the **right** screen reads touch inputs for the **left** screen.
3. If I add the `--no-same-owner` to the tar command, all the files extract properly, but the **left** screen is a static mess of colors and the **right** screen does not respond to touch _(from what I can gather)_

_I attached my console log to show the chown warning_
[console.txt](https://github.com/WOA-Project/SurfaceDuo-Guides/files/8238334/console.txt)

**Comment by anuwrag** [comment]
Inceasing the `esp` drive space from  `mkpart esp fat32 51.9MB 300MB` to  `mkpart esp fat32 51.9MB 400MB` solved this problem. The miminimum required space as stated is 256MB. I think it causes fragmenting issues when formating with 4kB FAT32.

**Comment by JengaMasterG** [comment]
That solves the issue!
