### ISSUE TITLE
No SM8150_EFI.fd file

### ISSUE THREAD

**Issue by kenpc-git** [WOA-Project/SurfaceDuo-Guides#31]
Downloading the zip just contains a file called 
uefi.img

**Comment by kenpc-git** [comment]
"Merging patched kernel image with the UEFI firmware" makes no sense

**Comment by gus33000** [comment]
Hi this was removed in the previous UEFI release due to known issues with secureboot, it has no been fixed. See the latest uefi release for packages named with "FD"
