### ISSUE TITLE
stuck in wondows logo in the first boot-Due 1

### ISSUE THREAD

**Issue by mraz2023** [WOA-Project/SurfaceDuo-Guides#33]
after following the steps and installing all the drivers the windows stuck in it's first boot up and the circling dot keep circling noting is happing!

**Comment by daanta-real** [comment]
In my case at the every first boot directly after installed Windows I went through the same circling dot problem as you happened. I did forced reboot with the way pushing volume down + power button, and it got solved.

**Comment by mraz2023** [comment]
I actually did press those keys but it broked the installation and I had to format my X drive on duo and reinstall the windows, the 2nd time it did the same thing but I only pressed the power button only (not very long press) and it helped to push the installation through!
