### ISSUE TITLE
USB Mouse not working

### ISSUE THREAD

**Issue by Mirilali** [WOA-Project/SurfaceDuo-Guides#34]
How can i Setup Windows, if a USB Mouse is not working? 
I‘m in the menu, where i can select the Language/Country? 

Please help :/

**Comment by gus33000** [comment]
> How can i Setup Windows, if a USB Mouse is not working? 
> 
> I‘m in the menu, where i can select the Language/Country? 
> 
> 
> 
> Please help :/
> 
> 

You can do so using touch just fine. If touch is not working then you likely followed our guides incorrectly.

**Comment by Mirilali** [comment]
So toch is also working on duo 2 ?

I got an error with driver!

Could that be the problem?


Gustave Monce ***@***.***> schrieb am Di. 28. Feb. 2023 um
10:34:

**Comment by gus33000** [comment]
Yes. Be aware duo 2 requires windows vnext (dev channel only) to work at the moment.
