### ISSUE TITLE
When i try to install driver, there is a Erro Code shown below

### ISSUE THREAD

**Issue by Mirilali** [WOA-Project/SurfaceDuo-Guides#35]
![Uploading 1EEBDDD4-30B1-4EFB-BDB9-0C0065427C70.jpeg…]()

**Comment by gus33000** [comment]
![image](https://user-images.githubusercontent.com/3755345/222010879-1c5bfda1-f25f-426b-bc60-df4c2415d977.png)
hi it appears you may have sent the bug report a bit too quickly here, could you please retry sending this image?
