### ISSUE TITLE
Touch functionality using fingers and pen is lost when using the Surface Pen

### ISSUE THREAD

**Issue by lg1313lg** [WOA-Project/SurfaceDuo-Guides#41]
Every time I use the pen to write a note for a few minutes, the touch control will be broken, both the pen and hand could not touch. Log off and log on can fix the touch control. But if I don't have a mouse with me, I can do nothing to fix that. The only thing I could do is shutdown.
Sometimes other conditions may also cause the issue, but in these conditions, leave it there for a while the touch will back to work.Only when use the pen and cause this issue, leave it for a while could not make it back to work.

**Comment by gus33000** [comment]
https://github.com/WOA-Project/SurfaceDuo-Drivers/releases/tag/2305.45
