### ISSUE TITLE
Auto rotation not working on 22624

### ISSUE THREAD

**Issue by ArturoGC06** [WOA-Project/SurfaceDuo-Guides#45]
As the title suggests, auto rotation is not working for me on my Duo 1, although the option to lock the rotation appears, and the device seems to recognise when you rotate it, as the start menu hides when you rotate the device. Also if I manually enable the _SurfaceDisplayConfiguratorService_46b83_ service (which doesn't start automatically when logging in), everything seems the same, except that now I can't disable or enable rotation lock from the control center. Video of the issue (sorry for the quality, I have to compress it to fit the 10mb limit): 

https://github.com/WOA-Project/SurfaceDuo-Drivers/assets/76574534/8b4de4b2-f3d9-40aa-9b5a-e52ece189c07

I used the latest drivers and UEFI (2305.25), Windows 11 Insider Beta 22624.1690, used epsilon_vb definition file.

**Comment by gus33000** [comment]
Fixed in 2305.45. Thanks!

https://github.com/WOA-Project/SurfaceDuo-Drivers/releases/tag/2305.45
