### ISSUE TITLE
Windows 10x image file expired

### ISSUE THREAD

**Issue by EntropyRiser** [WOA-Project/SurfaceDuo-Guides#53]
ufile.io let me pay for a subscribe to download
![image](https://github.com/WOA-Project/SurfaceDuo-Guides/assets/82279347/193c2c57-c2ca-44a3-9c79-cd5f711e2bbf)

```[tasklist]
### Tasks
```

**Comment by gus33000** [comment]
We plan to make updated images soon, so we won't reupload these. No ETA to share

**Comment by EntropyRiser** [comment]
Is this expired image "V0" and the coming image "V1"? That's great if so and thanks for your contribution!
