### ISSUE TITLE
Replacing one of the Displays on a Surface Duo 2 results in lost touch functionality

### ISSUE THREAD

**Issue by Kelvin1314a** [WOA-Project/SurfaceDuo-Guides#58]
My Surface Duo 2 changed the screen on the left and the screen flashed when I turned it on and I couldn't enter the system. I learned that the hardware encrypted the code that will recognize the screen at startup. Is there any way to fix this problem by modifying the startup file? If so, what should I do? Did anyone tell me?

**Comment by gus33000** [comment]
Hi!

I'm sorry, i don't really understand at all the issue you're describing, (perhaps you're using a translator?). It does not really make much sense when reading, could you explain the issue differently or perhaps send pictures so we can understand better? There is no hardware encryption for "recognizing" screens...

**Comment by Kelvin1314a** [comment]
The left LCD screen of my surface duo2 is broken. I replaced it with a new LCD screen. After installing it, I found that it cannot be used. The screen is encrypted. How can I crack it?

**Comment by gus33000** [comment]
Ok now i understand better. This is not something this project has anything to do with however but i can give you pointers myself:

There's no encryption going on, surface duo display parts and the digitizer is controlled by a single ic on the motherboard that is custom and not encrypted either. The controller ic has a map created with two displays calibrated at the factory and bounded together. Replacing one of them would invalidate said mapping, causing the controller to fall into factory mode. The only way for you to get around this is to acquire the programming firmware for the factory mode of the G6 chip, as well as the toolboxone digitizer tool built specifically to recalibrate or alter the mapping.

I however cannot help you with acquiring both of these myself, and there's no public material offered by microsoft to do this for you.
