### ISSUE TITLE
Overflash an already existing  partitioned SD 1? Possible or need to restore back?

### ISSUE THREAD

**Issue by jackonod** [WOA-Project/SurfaceDuo-Guides#71]
Can I ask you some perhaps basic. I just installed Windows 11 24h2 ffu to my Surface duo original 128 through MStorer WOA manager, half splitted. But now I realized I'd like to flash more the windows 10x Neo version! Do I need to revert back with deleting the already partitioned version, or I can just overflash the new image through that manager??? (the 10x Neo .ffu also same half parted, and recommended to 128 gb 1st gen Duo - which I have). Thank you your answer!

**Comment by gus33000** [comment]
You can flash FFU files how many times you want, when you want, where you want and how you want. The state of the phone does not matter.
